### ISSUE TITLE
Bump `dwn-sdk-js` to `0.1.0`

### ISSUE THREAD

**Issue by mistermoe** [TBD54566975/dwn-proxy-js#33]
`0.1.0` includes a breaking change that requires explicitly providing `messageStore`, `dataStore` and `eventLog`. [example here](https://github.com/tbd54566975/dwn-sdk-js#usage)

**Comment by KendallWeihe** [comment]
on this note, I've definitely not been following proper semver in the `dwn-proxy-js` but cause nobody is really using it... just recognizing that is to come 😅
